name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install octave
        run: sudo apt install -y octave
      - name: Run test
        run: cd MultiCamSelfCal && octave gocal.m --config=../strawlab/test-data/DATA20100906_134124/no-global-iterations.cfg

  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install octave, python and pip
        run: sudo apt install -y octave python3 python3-pip
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Install Python MCSC wrapper
        run: pip3 install -e .
      - name: Install pytest testing framework
        run: pip3 install pytest
      - name: Test Python wrapper
        run: pytest
